off-message: '&8[&2Gamerica&eFly&8] &3You can no longer fly.'
on-message: '&8[&2Gamerica&eFly&8] &bYou can fly now. Be free!'
worlds:
#  Creates this mini-game world Should Be the same as minigame:
  name: "Test"
#  Minigame world
  minigame: "Test"
#  Just to check if that's the same world
  main: "world"
  nether: "world_nether"
  end: "world_the_end"
  numberofplayers: 1

quests:
  kill:
    quest1:
      name: Zombieslayer
      description: Kill a zombie
      reward: 100
      target:
        type: ZOMBIE
        count: 1
    quest2:
      name: Genocide
      description: Kill 5 villagers
      reward: 420
      target:
        type: VILLAGER
        count: 5
    quest3:
      name: Kill Squidys
      description: Kill 1 squid
      reward: 10
      target:
        type: SQUID
        count: 1
  item:
    quest1:
      name: Squid
      description: Collect Squid ink
      reward: 100
      target:
        type: INK_SAC
        count: 1
    quest2:
      name: Apples
      description: get 5 apples
      reward: 420
      target:
        type: APPLE
        count: 5