undeadsword:
  zombie: 100
  skeleton: 100

#LAUNCH PADS
launchpads:
  enable: true #enable or disable launchpads
  message: false #have a message sent when they launch
  launch-message: '&9Whooooosh!!'

  #FULL BLOCK NAME LIST: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  top-block: 'AIR' #typically, a pressure plate or carpet
  under-block: 'SLIME_BLOCK'
  disable-fall-damage: true

#NODES/ BREAK BLOCKS
nodes:
  time-delays:
    dirt/stone/cobblestone: 60
    enddelay: 25
#    ENABLE RELOADING OF BLOCKS
  enable: true
  messages: true
  message: "If you want to not have it stay there, then press shift and destroy it"
#  Make it an indestructible block
  breakmaterial: "bedrock"
#  ADD BLOCKS IN UPPERCASE AND SPACES TO _
  dirttypes:
    - "DIRT"
    - "STONE"
    - "GRASS_BLOCK"
    - "CLAY"
    - "COBBLESTONE"
  endtypes:
    - "END_STONE"
    - "END_STONE_BRICKS"
#    - ""

#CONFIG RELOADS
reload:
  message:
    #You can add more if you like!
    - "&a Reloaded&c have fun"
#    -

#OFFHAND

offhand:
  enable: true
  offhand-message:
    enable: true
    message:
      - "&a Sorry Offhand Disabled"
#     -

#NPC
#Message2: "Hello There"
#Message: "General Kenobiiii"